### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by dajor** [Fellow-Consulting-AG/InforHomepageIDM#1]
We need to improve the design.

**Comment by farooqahmedkhan** [comment]
@dajor can we have to definite requirements in this, to help with exact timeline. As per the email shared in morning, is this final points
   - Improve header as per screenshots shared by Stephanie (Adding gradient and smaller icons)
     **Required** : Photoshop file needed so that we can add exact icons and gradient
     
If there are any points, please mention.

**Comment by farooqahmedkhan** [comment]
Design has been provided as per requirements
