### ISSUE TITLE
Keyboard Support Edit 

### ISSUE THREAD

**Issue by dajor** [Fellow-Consulting-AG/InforHomepageIDM#10]
When I am in the table i can use the right mouse to Edit ( Bearbeiten) the record or can press Strg+O to edit the attributes

**Comment by farooqahmedkhan** [comment]
Clear that we need to add a `right-click` support on table row OR `Ctrl + O` to move into Bearbeiten mode,

**Comment by farooqahmedkhan** [comment]
But will add it to estimation , once clear on the previous issue of widget modes based on top bar.

**Comment by farooqahmedkhan** [comment]
Keyboard support has been added
  - `Ctrl` + `UP` & ``DOWN` to move through the rows
  - `Ctrl` + `E` to enter edit & `Esc` to exit from this mode
  - `Ctrl` + `K` to enter eAkte & `Esc` to exit from this mode
