### ISSUE TITLE
Attributes in IDM

### ISSUE THREAD

**Issue by dajor** [Fellow-Consulting-AG/InforHomepageIDM#5]
Please create the attributes in IDM 
[Attribut.docx](https://github.com/Fellow-Consulting-AG/InforHomepageIDM/files/6264777/Attribut.docx)

Attribute Characteristic Mandatory Format 
Document type (IDM) "eExecution" Yes Text
Date/Time (attachment of document) Date Yes Text
Date of receipt Date Yes Text
Sender "Inbox" Yes Text
Leading cash reference Text No TBD
Cash reference Text No TBD
RLC Text No TBD
User ID Text Yes Text
Debtor ID Text No TBD
Debtor name Text No Text
Debtor First Name Text No Text
Document type Designation Text Yes Text
Document characteristic Return "Return" or "No" No Text
Document characteristic "External" Yes Text
DR number Text No TBD
Name of senior judicial officer (GV) / GV Text No Text
Name of the GV Text No Text
Address and telephone number of the GV Text No Text
Amount of the cost invoice in € Currency No TBD
Comment Text No Text
Validated for table of contents y/n Yes TBD

**Comment by farooqahmedkhan** [comment]
I will be needing assistance to understand this first in tomorrow's standup before estimation.

**Comment by mruckdaes** [comment]
The document type called EMA_Rücklauf was created with all the necessary attributes
Three example documents were added as well - they all start with Rücklauf
