### ISSUE TITLE
Table 

### ISSUE THREAD

**Issue by dajor** [Fellow-Consulting-AG/InforHomepageIDM#6]
in the Table we have this columns form the IDM

Feldname | Format | Quellle
-- | -- | --
Vertretung: | Haken   für ja, sonst leer | TBD
Datum   des Eingangs: | tt.mm.jj | IDM
Absender: | Text | IDM
Kassenzeichen: | Zahlen   plus u.U. Buchstaben | IDM
Nachname   (Schuldner) | Text | IDM
Vorname   (Schuldner) | Text | IDM
Eingang   (Dokumentbezeichnung) | Text | IDM

**Comment by dajor** [comment]
RIght now i not see this Feldname in the Table
<img width="713" alt="Bildschirmfoto 2021-04-06 um 15 14 33" src="https://user-images.githubusercontent.com/922524/113716412-de3d3900-96ea-11eb-909c-b1747d51a380.png">

**Comment by farooqahmedkhan** [comment]
The columns are exactly as provided. The task list API if provided will attach the data to it
